testenv: pass targets to osmo-dev's gen_makefile
Pass the targets we are about to build to osmo-dev's gen_makefile
script. This has two advantages:

1) Check early if a target isn't known by the current osmo-dev version,
   displaying a useful error to the user instead of just failing during
   make later on:

     ERROR: filter_projects_deps_targets: can't find project osmo-new-project in projects_deps!

     [testenv] gen_makefile.py from osmo-dev failed!
     [testenv] Your osmo-dev.git clone might be outdated, try:
     [testenv] $ git -C /home/user/code/osmo-dev pull

2) Parsing the generated Makefile when running "make" after generating
   it doesn't cause a noticable delay anymore. On my machine (with many
   Osmocom git repos cloned in osmo-dev's src dir) it went from several
   seconds to instantly.

Depends: osmo-dev I89bb60e94dd03606dbba5a3609d5e1a95993af5b
Change-Id: Ib2d8802b305f145d27aab3c1cc3129709b93d93d