bsc-nat: add 'Native_FunctionDefs.cc' to regen_makefile.sh
Some modules from library depend on these native functions.
Without them the compilation fails during linkage:

  Native_Functions.so: undefined reference to `Native__Functions::f__str__tolower(CHARSTRING const&)'
  Native_Functions.so: undefined reference to `Native__Functions::f__inet__hntoa(OCTETSTRING const&)'
  Native_Functions.so: undefined reference to `Native__Functions::f__inet__haddr(CHARSTRING const&)'
  BSSMAP_Templates.so: undefined reference to `Native__Functions::f__inet6__addr(CHARSTRING const&)'
  BSSMAP_Templates.so: undefined reference to `Native__Functions::f__inet__addr(CHARSTRING const&)'
  Native_Functions.so: undefined reference to `Native__Functions::f__str__toupper(CHARSTRING const&)'
  Native_Functions.so: undefined reference to `Native__Functions::f__inet__ntoa(OCTETSTRING const&)'
  collect2: error: ld returned 1 exit status
  make[1]: *** [BSCNAT_Tests] Error 1

Change-Id: I81227db58850375f0ce48e5c6e013381291a5904