testenv: use --autoreconf-in-src-copy by default
Pass --autoreconf-in-src-copy to osmo-dev's gen_makefile.py by default,
so we can always avoid errors related to:

* running "./configure" in-tree and out-of-tree (results in "configure:
  error: source directory already configured; run "make distclean" there
  first")
* running "./configure" / "autoreconf" with different autotools versions
  (on host system and in podman container)

I've kept is as experimental flag at first for better testing, but make
it the default now as it seems to work reliably.

The old make dir is cleaned up when the user runs "./testenv.py clean"
the next time.

Related: osmo-dev I18ac50e3441df81e1fe7d8d5321df7e80ab9c650
Change-Id: I41e1fb534e253ddb43f266d73485b83259a8aa40