testenv: podman: add libnftables-dev
This is required for building osmo-s1gw from source in podman,
otherwise:

  /home/user/.cache/osmo-ttcn3-testenv/podman/make3/osmo-s1gw/default/lib/enftables/c_src/enftables.c:16:10: fatal error: nftables/libnftables.h: No such file or directory
     16 | #include <nftables/libnftables.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.

Change-Id: I0ae94f73f0875048d9a71d1582627e57e60425c6