selftest: add missing Native_FunctionDefs.cc
Fix for:
/usr/bin/ld: Native_Functions.so: undefined reference to `Native__Functions::f__str__tolower(CHARSTRING const&)'
/usr/bin/ld: Native_Functions.so: undefined reference to `Native__Functions::f__inet__hntoa(OCTETSTRING const&)'
/usr/bin/ld: Native_Functions.so: undefined reference to `Native__Functions::f__inet__haddr(CHARSTRING const&)'
/usr/bin/ld: BSSMAP_Templates.so: undefined reference to `Native__Functions::f__inet6__addr(CHARSTRING const&)'
/usr/bin/ld: BSSMAP_Templates.so: undefined reference to `Native__Functions::f__inet__addr(CHARSTRING const&)'
/usr/bin/ld: Native_Functions.so: undefined reference to `Native__Functions::f__str__toupper(CHARSTRING const&)'
/usr/bin/ld: Native_Functions.so: undefined reference to `Native__Functions::f__inet__ntoa(OCTETSTRING const&)'

Related: OS#5252
Change-Id: I73c225f6699cd272b3eeffb249f3dddd2048bc01