hlr: pyhss: run the pyhss_hss service
Database preparations used to be done in PyHSS by all services if they
noticed that this was needed. The time between checking and creating the
tables caused a race condition where two services attempting to create
tables at the same time will result at one of them failing, we have seen
this in our ttcn3-hlr-test-pyhss jobs sometimes:

  [Database] [DEBUG] Table apn already exists
  [Database] [DEBUG] Table auc already exists
  [Database] [DEBUG] Table subscriber already exists
  …
  [testenv][pyhss] pyhss_gsup: setup script failed

I have fixed this upstream by letting only the main service (pyhss_hss)
prepare the database:
https://github.com/nickvsnetworking/pyhss/commit/8b8a2202c345fbb7262c9d07d03003cd2fdb819f

This means that we now need to run the pyhss_hss service in the HLR
tests, so pyhss_gsup doesn't fail with:

  [Database] [INFO] Waiting for the main service to prepare the database
  ERROR: 127.0.0.1:4222 did not become available within 5s!
  [testenv][pyhss] pyhss_gsup: setup script failed

Change-Id: I4fe689c8d8617432175ba403b45021c0f646970b