pgw: add missing BSSGP_EncDec.cc
Fix for:
/usr/bin/ld: BSSGP_Types_part_4.so: undefined reference to `BSSGP__Types::dec__PDU__BSSGP(OCTETSTRING const&)'
/usr/bin/ld: Osmocom_Gb_Types.so: undefined reference to `BSSGP__Types::enc__PDU__BSSGP(BSSGP__Types::PDU__BSSGP const&)'

Related: OS#5252
Change-Id: I010df10396d264e67bd8c712daafcfb79262ece2