library/MGCP_Emulation: Fix Dynamic test case error returning unbound value
As spotted today while running HNBGW_Tests.TC_rab_assignment, probably after upgrade to titan 11:
17:54:36.223786 1570 MGCP_Emulation.ttcn:241 Dynamic test case error: Copying an unbound charstring value.

The error happened because in that failure path the component running
the function was not stopped, and hence an unset variable was returned.
Hence, make sure we tear everything down (including component going
through the failure path).

Change-Id: Id1d28924e90ed80199b61a143dac35fc6f50de68