sgsn/SGSN_Tests_SNS.cfg: adjust to recent changes
Fix this error:
  Error: Error message was received from HC at 10.0.2.100 [10.0.2.100]: Error while setting parameter field 'SGSN_Tests.mp_ranap_cfg[0].sctp_addr' to '{ 23908, "127.0.0.103", 2905, "127.0.0.200" }': Non existent field name in type @RAN_Adapter.RAN_Configuration: sctp_addr

Fixes: 0cdd73a8 ("Split SCCP_Adapter out of RAN_Adapter")
Change-Id: I62a1188aa3346fda3f0674296629ade51a02088f